Revert 264313 "Add activity recording capability to gcm internal..."
This caused a compile error on the Win x64 builder:

http://build.chromium.org/p/chromium.win/builders/Win%20x64%20Builder/builds/17353/steps/compile/logs/stdio

FAILED: ninja -t msvc -e environment.x64 -- C:\b\build\goma\gomacc.exe "C:\b\depot_tools\win_toolchain\vs2013_files\VC\bin\amd64\cl.exe" /nologo /showIncludes /FC @obj\google_apis\gcm\tools\mcs_probe.mcs_probe.obj.rsp /c ..\..\google_apis\gcm\tools\mcs_probe.cc /Foobj\google_apis\gcm\tools\mcs_probe.mcs_probe.obj /Fdobj\google_apis\gcm\mcs_probe.cc.pdb 
c:\b\build\slave\cr-win-rel-x64\build\src\google_apis\gcm\tools\mcs_probe.cc(309) :error C2661: 'gcm::MCSClient::MCSClient' : no overloaded function takes 4 arguments
ninja: build stopped: subcommand failed.


> Add activity recording capability to gcm internals page. User can refresh, start/stop recording, and clear recording logs.
> Also added more information to the device info section and fixed a bug there.
> 
> arv: owner review of chrome/browser/resources/*.
> jianli & fgorski please review the rest of the code, and zea for owner review of these code. 
> 
> BUG=341256
> 
> Review URL: https://codereview.chromium.org/202083005

TBR=juyik@chromium.org

Review URL: https://codereview.chromium.org/240583002

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: f76dc353b84dcdd78de944db874424c4f4b14b95